#!/usr/bin/env python3
"""Generate packages/dme-flash/src/regionTable.generated.ts from the CSL 0401 image.

The table is DATA in the firmware, so it is generated rather than typed by hand: a
transcription error here is an address the flasher would accept that the ECU rejects,
or worse, one it would erase. regionMap.test.ts re-derives it from the BIN and fails
if this file has drifted.

Layout proven by disassembly - see docs/region-map.md.
"""
import os, sys

BIN = os.environ.get('CSL_0401_BIN',
    r"C:\Users\kazuh\CSL_0401_Binary_Disassembly_Notes\Full 211323000401PD31_TERRA.bin")
BASE, STRIDE, MAX_ENTRIES = 0x3AD6, 10, 0x41
OUT = os.path.join(os.path.dirname(__file__), '..', '..',
                   'packages', 'dme-flash', 'src', 'regionTable.generated.ts')

def u32(b, o): return int.from_bytes(b[o:o+4], 'big')

def read_entries(data):
    out = []
    for i in range(MAX_ENTRIES):
        o = BASE + i * STRIDE
        e = data[o:o+STRIDE]
        if len(e) < STRIDE:
            raise SystemExit(f'image too short for entry {i} at 0x{o:X}')
        out.append((e[0], e[1], u32(e, 2), u32(e, 6)))
    return out

def main():
    if not os.path.exists(BIN):
        raise SystemExit(f'image not found: {BIN}\nset CSL_0401_BIN to override')
    data = open(BIN, 'rb').read()
    entries = read_entries(data)
    lines = [
        '// GENERATED by tools/analysis/gen_region_table.py - do not edit by hand.',
        f'// Source: {os.path.basename(BIN)}  table @ 0x{BASE:04X}, stride {STRIDE}, {MAX_ENTRIES} entries.',
        '// Layout and address semantics: docs/region-map.md',
        '',
        'export interface RegionTableEntry {',
        '    /** Segment selector - the DS2 programming control byte. */',
        '    readonly id: number;',
        '    /** 0xFF = address used as-is; otherwise the entry matches (address >> 16) & 0xF0. */',
        '    readonly variant: number;',
        '    readonly start: number;',
        '    readonly end: number;',
        '}',
        '',
        f'export const REGION_TABLE_BASE = 0x{BASE:04X};',
        f'export const REGION_TABLE_STRIDE = {STRIDE};',
        f'export const REGION_TABLE_MAX_ENTRIES = 0x{MAX_ENTRIES:02X};',
        '',
        '/** Hard cap the firmware applies to a single transfer (flash_req_parse). The DS2 framing',
        '  * cap is lower and is what actually binds - see docs/region-map.md. */',
        'export const FIRMWARE_BLOCK_CAP = 0x80;',
        '',
        'export const REGION_TABLE: readonly RegionTableEntry[] = [',
    ]
    for i, (rid, var, s, e) in enumerate(entries):
        note = ''
        if s == 0 and e == 0:
            note = '  // empty slot'
        elif e <= s:
            note = '  // end <= start: unreachable by design'
        lines.append(f'    {{ id: 0x{rid:02X}, variant: 0x{var:02X}, '
                     f'start: 0x{s:06X}, end: 0x{e:06X} }},{note}'.replace('},  //', '}, //'))
    lines += ['] as const;', '']
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'wrote {os.path.relpath(OUT)} ({len(entries)} entries)')

if __name__ == '__main__':
    main()
